### ISSUE TITLE
dockerでのdatabase関連のエラーを無理やり突破する覚え書き

### ISSUE THREAD

**Issue by osamummu** [hamuhamu5hamu/attendance_system#9]
Dockerで`docker -p 3000:3000 <image> bin/bundle exec rails s`というコマンドで動かそうとすると、Databaseに関連したエラーが修正するたびに次々と出てなかなか起動できませんでした。

これは、取り敢えず動かすために行った修正の自分用メモです。
セキュリティとかは考えないで行ったので、本番環境で以下の修正をしたものを動かすべきではないと思います。

まず、Dockerfileを以下のものに置き換えます。元のファイルから変更した部分に、CHANGEDというアノテーションを入れています。
```Dockerfile
# syntax = docker/dockerfile:1

# This Dockerfile is designed for production, not development. Use with Kamal or build'n'run by hand:
# docker build -t my-app .
# docker run -d -p 80:80 -p 443:443 --name my-app -e RAILS_MASTER_KEY=<value from config/master.key> my-app

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.1.4
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set production environment
ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development"

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# CHANGED: 追加したけど、また消した
RUN gem install bundler -v '~> 2.5'

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Copy application code
COPY . .

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile app/ lib/

# CHANGED:
RUN rm ./config/credentials.yml.enc
RUN ./bin/rails credentials:edit

# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

# CHANGED:
RUN bundle exec rails db:create
RUN bundle exec rails db:migrate
RUN bundle exec rails db:migrate RAILS_ENV=production
RUN bundle exec rails db:migrate:status
RUN bundle exec rails db:migrate:status RAILS_ENV=production
RUN chmod -R 777 .




# Final stage for app image
FROM base

# Copy built artifacts: gems, application
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
USER 1000:1000

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/rails", "server"]

```

次に、config/database.yml を以下のものに置き換えます。
```yml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db

development:
  <<: *default
  database: storage/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: storage/test.sqlite3


# SQLite3 write its data on the local filesystem, as such it requires
# persistent disks. If you are deploying to a managed service, you should
# make sure it provides disk persistence, as many don't.
#
# Similarly, if you deploy your application as a Docker container, you must
# ensure the database is located in a persisted volume.
production:
  <<: *default
  database: path/to/persistent/storage/production.sqlite3
# CHANGED: uncommented out the above line
```

最後に、config/environments/production.rb の中の、
```ruby
config.force_ssl = true
```
という行を、
```ruby
config.force_ssl = false
```
に変えます。

これで、`docker build . -t <tag> && docker run -p 3000:3000 <tag> bin/bundle exec rails s`を実行して、ブラウザで、http://0.0.0.0:3000にアクセスするときちんとページが開きます。
